-- CreateTable
CREATE TABLE "GenItem" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "kind" INTEGER NOT NULL DEFAULT 99,
    "modifier" REAL NOT NULL DEFAULT 1,
    "userId" INTEGER NOT NULL,
    CONSTRAINT "GenItem_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
